### ISSUE TITLE
Trying to use with paymaster

### ISSUE THREAD

**Issue by mm-zk** [popzxc/alloy-zksync#7]
I've added the custom method 'with_paymaster' to set paymaster params.

But then it fails when I try to send it as transaction wtih :

called `Result::unwrap()` on an `Err` value: ErrorResp(ErrorPayload { code: -32602, message: "Invalid params: invalid type: string \"0x1234\", expected a sequence.", data: None })

where 0x1234 was the value inside paymaster input params.

probably some issue with bytes serialization

**Comment by mm-zk** [comment]
my current workaroudn was to do:

```
fn serialize_foo<S: serde::Serializer>(bytes: &Bytes, serializer: S) -> Result<S::Ok, S::Error> {
    serializer.serialize_bytes(&bytes.0)
}
```

and then

pub struct PaymasterParams {
    pub paymaster: Address,
    #[serde(serialize_with = "serialize_foo")]
    pub paymaster_input: Bytes,
}

**Comment by popzxc** [comment]
Ah, right, serializing `Bytes` is different from serializing `Vec<u8>` in RLP. It's [handled here](https://github.com/popzxc/alloy-zksync/blob/main/src/network/unsigned_tx/eip712/meta.rs#L28) for factory deps, but I forgot to implement the same fix for `paymaster_input`. 

If you will have time to submit a fix, that'd be greatly appreciated. Otherwise, I'll try to work on it this week.
